-- AlterTable
ALTER TABLE `activities`
  MODIFY COLUMN `type` ENUM('NOTE', 'STATUS_CHANGE', 'DOCUMENT', 'HANDOFF', 'MENTION', 'CREATED', 'PRIORITY_CHANGE', 'DUE_DATE_CHANGE', 'DESCRIPTION_CHANGE', 'ASSIGNEE_CHANGE', 'TAG_CHANGE') NOT NULL;
