// O de-para padrão da 41 — categoria do Omie para grupo do DRE.
//
// ─── CHUTE, 11/09 — reversível ──────────────────────────────────────────────
//
// Extraído da planilha da Irriga, e adotado como **modelo padrão** que cada
// empresa herda e ajusta. A alternativa seria montar do zero por cliente; esta
// aposta é a que faz o segundo cliente começar com 90% do trabalho pronto, e o
// custo de errar é uma linha no lugar errado, visível na tela.
//
// As categorias são texto do Omie, com os erros de digitação preservados
// ("anáisdeaço", "Comissões  Produção" com dois espaços). Corrigi-los aqui
// quebraria o casamento com o dado real — `chaveDaCategoria` normaliza espaço,
// acento e caixa, e só isso.

export const MAPEAMENTO_PADRAO: { categoria: string; grupo: string }[] = [
  { categoria: "Clientes - Venda de sucata", grupo: "receita_bruta" },
  { categoria: "Clientes - Venda de Mercadoria Fabricadas", grupo: "receita_bruta" },
  { categoria: "Impostos Estaduais - ICMS", grupo: "impostos" },
  { categoria: "Impostos Federais - IRPJ", grupo: "impostos" },
  { categoria: "Impostos Federais - COFINS", grupo: "impostos" },
  { categoria: "Impostos Federais - CSSL", grupo: "impostos" },
  { categoria: "Impostos Federais - PIS", grupo: "impostos" },
  { categoria: "Aluguel de Equipamentos", grupo: "cmv" },
  { categoria: "Compra de consumiveis", grupo: "cmv" },
  { categoria: "Compra de Consumíveis - Gas de solda", grupo: "cmv" },
  { categoria: "Compra de consumiveis - gás empilhadeira", grupo: "cmv" },
  { categoria: "Compra de consumiveis - Solda", grupo: "cmv" },
  { categoria: "Compra de embalagens", grupo: "cmv" },
  { categoria: "Compra de Materia Prima", grupo: "cmv" },
  { categoria: "compra de matéria prima - anéisdeaço", grupo: "cmv" },
  { categoria: "Compra de Matéria Prima - Borracha", grupo: "cmv" },
  { categoria: "Compra de Matéria Prima - Bobina", grupo: "cmv" },
  { categoria: "Compra de Matéria Prima - Chapa de aço", grupo: "cmv" },
  { categoria: "Compra de Materia Prima - Parafusos", grupo: "cmv" },
  { categoria: "Compra de Materia Prima - Secundaria", grupo: "cmv" },
  { categoria: "Compra de Materia Prima - Tubo de aço", grupo: "cmv" },
  { categoria: "Compra de Matéria Prima - Tubo Helicoidal", grupo: "cmv" },
  { categoria: "Compra de material para uso e consumo", grupo: "cmv" },
  { categoria: "Compra de Mercadoria para Revenda", grupo: "cmv" },
  { categoria: "Compra de Serviços", grupo: "cmv" },
  { categoria: "Devolução de Venda", grupo: "cmv" },
  { categoria: "Frete", grupo: "cmv" },
  { categoria: "Impostos Retidos Serviços Tomados", grupo: "cmv" },
  { categoria: "Convenio Depen", grupo: "mao_de_obra" },
  { categoria: "Serviço de terceiro - Corte a laser", grupo: "mao_de_obra" },
  { categoria: "Serviço de terceiro - Frete Interno", grupo: "mao_de_obra" },
  { categoria: "Serviço de terceiro - Galvanização", grupo: "mao_de_obra" },
  { categoria: "Serviço de terceiro - Projetos", grupo: "mao_de_obra" },
  { categoria: "Serviços de Correção de Produção", grupo: "mao_de_obra" },
  { categoria: "Serviços de terceiros", grupo: "mao_de_obra" },
  { categoria: "Serviço de terceiro - Tornearia", grupo: "mao_de_obra" },
  { categoria: "Aluguel", grupo: "comerciais" },
  { categoria: "Aluguel de veículos", grupo: "comerciais" },
  { categoria: "Folha de pagamento Comercial", grupo: "comerciais" },
  { categoria: "Comissões", grupo: "comerciais" },
  { categoria: "Comissões de Vendas", grupo: "comerciais" },
  { categoria: "Comissões por  indicação", grupo: "comerciais" },
  { categoria: "Comissões  Produção", grupo: "comerciais" },
  { categoria: "Marketing", grupo: "comerciais" },
  { categoria: "Despesas de Viagens", grupo: "comerciais" },
  { categoria: "Alimentação/Almoço", grupo: "pessoal" },
  { categoria: "Assistência Médica", grupo: "pessoal" },
  { categoria: "Folha de pagamento Produção", grupo: "pessoal" },
  { categoria: "13º Salário", grupo: "pessoal" },
  { categoria: "Adiantamento", grupo: "pessoal" },
  { categoria: "Férias", grupo: "pessoal" },
  { categoria: "Salários - Tracz", grupo: "pessoal" },
  { categoria: "Rescisões", grupo: "pessoal" },
  { categoria: "Epis", grupo: "pessoal" },
  { categoria: "Vale Refeição", grupo: "pessoal" },
  { categoria: "Vale Transporte", grupo: "pessoal" },
  { categoria: "Adiantamento - Blindagem", grupo: "pessoal" },
  { categoria: "Adiantamento - Tracz", grupo: "pessoal" },
  { categoria: "Salários - Blindagem", grupo: "pessoal" },
  { categoria: "FGTS - Tracz", grupo: "pessoal" },
  { categoria: "FGTS - Blindagem", grupo: "pessoal" },
  { categoria: "FGTS", grupo: "pessoal" },
  { categoria: "INSS", grupo: "pessoal" },
  { categoria: "IRRF", grupo: "pessoal" },
  { categoria: "Despesas com Farmácia", grupo: "pessoal" },
  { categoria: "Uniformes e EPIs", grupo: "pessoal" },
  { categoria: "Outros Benefícios", grupo: "pessoal" },
  { categoria: "Seguro de Vida", grupo: "pessoal" },
  { categoria: "Pró-labore", grupo: "diretoria" },
  { categoria: "Benefícios alimentação - sócios", grupo: "diretoria" },
  { categoria: "Despesas de Viagens (Sócios)", grupo: "diretoria" },
  { categoria: "Energia Elétrica", grupo: "administrativas" },
  { categoria: "Manutenção Predial", grupo: "administrativas" },
  { categoria: "Contabilidade", grupo: "administrativas" },
  { categoria: "Equipamentos de Informática", grupo: "administrativas" },
  { categoria: "Softwares - Licença e aluguel", grupo: "administrativas" },
  { categoria: "Compra de combustível", grupo: "administrativas" },
  { categoria: "Internet", grupo: "administrativas" },
  { categoria: "Sindicatos", grupo: "administrativas" },
  { categoria: "Telefonia", grupo: "administrativas" },
  { categoria: "Material de Escritório", grupo: "administrativas" },
  { categoria: "Transporte", grupo: "administrativas" },
  { categoria: "Taxas e licenças administrativas e profissionais", grupo: "administrativas" },
  { categoria: "Manutenção veículos", grupo: "administrativas" },
  { categoria: "Manutenção de maquinas e equipamentos", grupo: "administrativas" },
  { categoria: "Manutenção de móveis/utensilios", grupo: "administrativas" },
  { categoria: "Instalações de Máquinas e Equipamentos", grupo: "administrativas" },
  { categoria: "Medicina ocupacional e Segurança do Trabalho", grupo: "administrativas" },
  { categoria: "Reembolso de Despesa Com MKT", grupo: "administrativas" },
  { categoria: "Devoluções de Vendas de Mercadoria", grupo: "administrativas" },
  { categoria: "Despesas com Protestos de fornecedores", grupo: "administrativas" },
  { categoria: "Tarifas Bancárias", grupo: "financeiras" },
  { categoria: "IOF", grupo: "financeiras" },
  { categoria: "Máquinas e Equipamentos", grupo: "investimentos" },
  { categoria: "Compra de ativo imobilizado", grupo: "investimentos" },
  { categoria: "Consultoria", grupo: "investimentos" },
  { categoria: "Devoluções de Compra de Matéria Prima", grupo: "outras_receitas" },
  { categoria: "Empréstimos Bancários", grupo: "outras_receitas" },
  { categoria: "Devolução de Pagamento Indevido", grupo: "outras_receitas" },
  { categoria: "Devoluções de Compra de Mercadoria de Revenda", grupo: "outras_receitas" },
  { categoria: "Antecipação de notas", grupo: "outras_despesas" },
  { categoria: "Cursos e Treinamentos", grupo: "outras_despesas" },
  { categoria: "Brindes", grupo: "outras_despesas" },
  { categoria: "Multas", grupo: "outras_despesas" },
  { categoria: "Outras Taxas", grupo: "outras_despesas" },
  { categoria: "Impostos Parcelados", grupo: "outras_despesas" },
  { categoria: "Distribuição de Lucros - Sócios", grupo: "outras_despesas" },
  { categoria: "Pagamento Indevido", grupo: "outras_despesas" },
  { categoria: "Pagamento de Empréstimos", grupo: "outras_despesas" },
];
